# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses: [10.0.0.7/24]
      gateway4: 10.0.0.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
  version: 2
